# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            gringo.io
tagline:          'My adventures in coding'
description:      'Geeking out with Ruby, Rails, Vim, and any other rabbit hole that comes along'
url:              http://gringo.io

author:
  name:           'Miles Starkenburg'
  url:            https://twitter.com/gring0cl

paginate:         5

# Custom vars
version:          1.0.0

github:
  url:            https://github.com/gringocl

twitter:
  url:            https://twitter.com/gring0cl
